# torchrec MovieLens Tutorial

In [6]:
# ! wget https://files.grouplens.org/datasets/movielens/ml-25m.zip
# %load_ext autoreload
%autoreload 2


## Table of contents
1. Instantiating MovieLens-25M dataset
2. Defining model
3. Training and evaluating model
4. Finding similar movies

## 1. Instantiating MovieLens-25M dataset

To start, we can load the MovieLens-25M dataset using `torchrec.datasets.movielens.movielens_25m`. The function loads just the user-movie ratings data in `ratings.csv` by default; we call the function with `include_movies_data=True` such that it adds movie data from `movies.csv` to each user-movie sample.

In [7]:
# from torchrec.datasets.movielens import movielens_25m

# dp = movielens_25m("ml-25m", include_movies_data=True)
from movielens import movielens_25m
dp = movielens_25m("s3://torchrec-movielens-dataset/", include_movies_data=True)

Let's check out a single sample.

In [8]:
next(iter(dp))

{'userId': 1,
 'movieId': 296,
 'rating': 5.0,
 'timestamp': 1147880044,
 'title': 'Pulp Fiction (1994)',
 'genres': 'Comedy|Crime|Drama|Thriller'}

Seems reasonable.

Next, we instantiate datapipes representing training and validation data splits and apply shuffling and batching.

In [9]:
from torchrec.datasets.utils import rand_split_train_val

train_dp, val_dp = rand_split_train_val(dp, 0.9)
batched_train_dp = train_dp.shuffle(buffer_size=int(1e5)).batch(8192)
batched_val_dp = val_dp.batch(8192)

Turns out that the integer user ids and movie ids referenced by the dataset aren't contiguous. Let's remap them to contiguous values so that we can use them with `torch.nn.Embedding` more easily downstream.

To do so, we first populate dictionaries that map movie and user ids to ids in contiguous ranges

In [10]:
# contig_movie_ids = {}
# contig_user_ids = {}
# movie_id_to_title_genre = {}

# available_movie_id = 0
# available_user_id = 0
# for sample in dp:
#     if sample["movieId"] not in contig_movie_ids:
#         contig_movie_ids[sample["movieId"]] = available_movie_id
#         available_movie_id += 1
#     if sample["userId"] not in contig_user_ids:
#         contig_user_ids[sample["userId"]] = available_user_id
#         available_user_id += 1
#     movie_id_to_title_genre[sample["movieId"]] = (sample["title"], sample["genres"])

, and then define a function `_transform` that uses those dictionaries to remap movie and user ids for a batch of data. While we're at it, we'll also have `_transform` reformat the batch as tensors representing user ids, movie ids, and labels (numerical movie ratings given by users).

In [11]:
unique_user_ids_num = 162541
unique_movie_ids_num = 59047

In [12]:
import torch
from threading import Lock

class Transform(object):
    def __init__(self):
        self._contig_movie_ids = {}
        self._contig_user_ids = {}
        self._movie_id_to_title_genre = {}
        
        self._lock = Lock()
        self._available_movie_id = 0
        self._available_user_id = 0
    
    def __call__(self, batch):
        self._update_ids(batch)
        return self._transform(batch)
        
    def _update_ids(self, batch):
        with self._lock:
            for sample in batch:
                if sample["movieId"] not in self._contig_movie_ids:
                    self._contig_movie_ids[sample["movieId"]] = self._available_movie_id
                    self._available_movie_id += 1
                if sample["userId"] not in self._contig_user_ids:
                    self._contig_user_ids[sample["userId"]] = self._available_user_id
                    self._available_user_id += 1
                self._movie_id_to_title_genre[sample["movieId"]] = (sample["title"], sample["genres"])
    
    def _transform(self, batch):
        user_ids = torch.tensor([self._contig_user_ids[sample["userId"]] for sample in batch], dtype=torch.int32)
        movie_ids = torch.tensor([self._contig_movie_ids[sample["movieId"]] for sample in batch], dtype=torch.int32)
        labels = torch.tensor([sample["rating"] for sample in batch], dtype=torch.float)
        return user_ids, movie_ids, labels
            

# def _transform(batch):
#     user_ids = torch.tensor([contig_user_ids[sample["userId"]] for sample in batch], dtype=torch.int32)
#     movie_ids = torch.tensor([contig_movie_ids[sample["movieId"]] for sample in batch], dtype=torch.int32)
#     labels = torch.tensor([sample["rating"] for sample in batch], dtype=torch.float)
#     return user_ids, movie_ids, labels

_transform = Transform()

Finally, we configure our training and validation datapipes to apply `_transform` to each batch of data using `map`.

In [13]:
preproc_train_dp = batched_train_dp.map(_transform)
preproc_val_dp = batched_val_dp.map(_transform)

At this point, `preproc_train_dp` and `preproc_val_dp` are set up to produce the data that our model expects.

In [14]:
next(iter(preproc_train_dp))

(tensor([  0,   0,   1,  ...,  27,  53, 109], dtype=torch.int32),
 tensor([   0,    1,    2,  ...,  515, 3289, 1688], dtype=torch.int32),
 tensor([3.5000, 4.0000, 5.0000,  ..., 4.5000, 4.5000, 5.0000]))

## 2. Defining model

Next, we define the model we're going to train. We'll go with a simplified two-tower model `TwoTowerModel` resembling a matrix factorization model that attempts to learn a low-rank approximation of the user-movie ratings matrix. More specifically, we want to find matrices $U \in \mathbb{R}^{u \times d}$ and $M \in \mathbb{R}^{m \times d}$ such that $U M^T \approx A$, where each row in $U$ represents a user embedding of dimension $d$ and each row in $M$ a movie embedding also of dimension $d$. Once we find matrices $U$ and $M$, we can infer the rating that the $i$-th user gives the $j$-th movie as $u_i^T \cdot m_j^T$, i.e. the dot product of the $i$-th row in $U$ and $j$-th row in $M$.

`TwoTowerModel` represents $U$ and $M$ as embedding tables — instances of `torch.nn.Embedding`.

In [15]:
class TwoTowerModel(torch.nn.Module):
    def __init__(self, num_embeddings_0, num_embeddings_1, embedding_dim):
        super().__init__()
        self.model_0 = torch.nn.Embedding(num_embeddings_0, embedding_dim)
        self.model_1 = torch.nn.Embedding(num_embeddings_1, embedding_dim)
    
    def forward(self, input):
        embeddings_0 = self.model_0(input[0])
        embeddings_1 = self.model_1(input[1])
        return torch.sum(embeddings_0 * embeddings_1, axis=1)

## 3. Training and evaluating model
We're ready to train our model. Let's instantiate the model we just defined

In [16]:
model = TwoTowerModel(
    unique_user_ids_num, #len(contig_user_ids),
    unique_movie_ids_num, #len(contig_movie_ids),
    32
)

, instantiate our loss function and optimizer

In [17]:
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1, momentum=0.9, weight_decay=1e-6)

, and define our train and test loops.

In [18]:
def train_loop(dp, model, loss_fn, optimizer):
    for batch, (users, movies, labels) in enumerate(dp):
        pred = model((users, movies))
        loss = loss_fn(pred, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 100 == 0:
            loss, current = loss.item(), batch * len(labels)
            print(f"loss: {loss:>7f}; batch: {batch}")

def test_loop(dp, model, loss_fn):
    test_loss = 0
    batch_count = 0
    with torch.no_grad():
        for batch, (users, movies, labels) in enumerate(dp):
            pred = model((users, movies))
            test_loss += loss_fn(pred, labels).item()
            batch_count += 1
    
    print(f"Test loss: {test_loss / batch_count}")

And now, we train.

In [ ]:
epochs = 3

for __ in range(epochs):
    train_loop(preproc_train_dp, model, loss_fn, optimizer)
    test_loop(preproc_val_dp, model, loss_fn)

loss: 45.422134; batch: 0
loss: 38.413521; batch: 100
loss: 34.630333; batch: 200
loss: 30.334789; batch: 300
loss: 30.588533; batch: 400
loss: 27.773775; batch: 500
loss: 27.661900; batch: 600
loss: 26.092945; batch: 700


We've got a trained model!

## 4. Finding similar movies
For kicks, let's see if we can use our model's trained embeddings to find movies that are most similar to some query movie. In theory, movies with embeddings that are similar should themselves be similar.

In [36]:
movie_id_to_title_genre = _transform._movie_id_to_title_genre
contig_to_movie_id = {v: k for k, v in _transform._contig_movie_ids.items()}


In [37]:
# contig_to_movie_id = {v: k for k, v in contig_movie_ids.items()}

def get_topk_sim_movies(movie_id, k=20):
    embedding = model.model_1(torch.tensor([contig_movie_ids[movie_id]]))
    movie_embeddings = model.get_parameter("model_1.weight")
    movie_similarities = torch.sum(embedding * movie_embeddings, axis=1) / torch.maximum(torch.norm(embedding) * torch.norm(movie_embeddings, dim=1), torch.ones(movie_embeddings.shape[0]) * 1e-12)
    topk_sim = torch.topk(movie_similarities, 20)
    contig_ids = topk_sim.indices.tolist()
    return [
        (*movie_id_to_title_genre[contig_to_movie_id[movie_id]], contig_to_movie_id[movie_id]) 
        for movie_id in contig_ids
    ]

In [38]:
# Drive
get_topk_sim_movies(88129)

KeyError: 45881

In [18]:
# Lost in Translation
get_topk_sim_movies(6711)

[('Lost in Translation (2003)', 'Comedy|Drama|Romance', 6711),
 ('Blade (1998)', 'Action|Horror|Thriller', 2167),
 ('O Brother, Where Art Thou? (2000)', 'Adventure|Comedy|Crime', 4027),
 ('Minority Report (2002)', 'Action|Crime|Mystery|Sci-Fi|Thriller', 5445),
 ('Bowling for Columbine (2002)', 'Documentary', 5669),
 ('Lord of War (2005)', 'Action|Crime|Drama|Thriller|War', 36529),
 ('Dark City (1998)', 'Adventure|Film-Noir|Sci-Fi|Thriller', 1748),
 ('Rocky (1976)', 'Drama', 1954),
 ('Best in Show (2000)', 'Comedy', 3911),
 ('Deliverance (1972)', 'Adventure|Drama|Thriller', 2871),
 ('Eternal Sunshine of the Spotless Mind (2004)',
  'Drama|Romance|Sci-Fi',
  7361),
 ('Crouching Tiger, Hidden Dragon (Wo hu cang long) (2000)',
  'Action|Drama|Romance',
  3996),
 ('Fahrenheit 9/11 (2004)', 'Documentary', 8622),
 ('Back to the Future Part III (1990)',
  'Adventure|Comedy|Sci-Fi|Western',
  2012),
 ('Boogie Nights (1997)', 'Drama', 1673),
 ('Run Lola Run (Lola rennt) (1998)', 'Action|Crime', 

In [21]:
# Ratatouille
get_topk_sim_movies(50872)

[('Ratatouille (2007)', 'Animation|Children|Drama', 50872),
 ('Harry Potter and the Goblet of Fire (2005)',
  'Adventure|Fantasy|Thriller|IMAX',
  40815),
 ('Toy Story 2 (1999)', 'Adventure|Animation|Children|Comedy|Fantasy', 3114),
 ('Ice Age (2002)', 'Adventure|Animation|Children|Comedy', 5218),
 ('Monsters, Inc. (2001)',
  'Adventure|Animation|Children|Comedy|Fantasy',
  4886),
 ('Harry Potter and the Chamber of Secrets (2002)', 'Adventure|Fantasy', 5816),
 ('Wedding Singer, The (1998)', 'Comedy|Romance', 1777),
 ('Armageddon (1998)', 'Action|Romance|Sci-Fi|Thriller', 1917),
 ('WALL·E (2008)', 'Adventure|Animation|Children|Romance|Sci-Fi', 60069),
 ('Finding Nemo (2003)', 'Adventure|Animation|Children|Comedy', 6377),
 ('Indiana Jones and the Temple of Doom (1984)',
  'Action|Adventure|Fantasy',
  2115),
 ('Signs (2002)', 'Horror|Sci-Fi|Thriller', 5502),
 ('Toy Story 3 (2010)',
  'Adventure|Animation|Children|Comedy|Fantasy|IMAX',
  78499),
 ('My Big Fat Greek Wedding (2002)', 'Comed

What do you think? Can we do better?